### ISSUE TITLE
JSON files: Data at the root level is invalid. Line 1, position 1.

### ISSUE THREAD

**Issue by bryanparke** [Microsoft/slow-cheetah#108] opened 2018-02-13 00:11 UTC
With any .json file that I attempt to preview the transform, I get the above error. Here is the sample input json:

{ "A" : { "A1" : "11" }, "B" : { "1B" : 12, "2B" : 22 }, "C" : { "C1" : 31, "C2" : 32 } }

No matter what, when I choose to preview the transform, the error is always "Data at the root level is invalid. Line 1, position 1."  It is as if it doesn't work with JSON files and is expecting XML? Taking a wild guess.

**Comment by bryanparke** [comment] 2018-02-13 16:26
I learned from some other issues that this error is happening when I do a Preview Transformation because the preview function appears to only work if the transform has an associated build / project configuration.  There are 2 "preview transform" options when you right click a transform file, the first one fails (no error), the second one fails with the error mentioned in the original post.  However, if I add a project config that matches the name of the transform, the preview works.

**Comment by icnocop** [comment] 2018-03-23 04:41
The [v2.5.48 release notes](https://github.com/sayedihashimi/slow-cheetah/releases/tag/v2.5.48) indicate that you have to manually uninstall the old version of SlowCheetah.

Would not uninstalling the old version cause the issue where you'd see two "Preview Transform" menu items?

**Comment by davilimap** [comment] 2018-04-25 18:25
@bryanparke If I'm not mistaken, that issue is with XDT, but your file is JSON. As @icnocop mentioned, you probably have the older install version of SlowCheetah that only works with XML files. Can you verify that you have the latest version of the extension (3.0.61)?

**Comment by TheMrAnderson** [comment] 2018-07-05 19:16
I'm having the same issue in an app that has never had the old version of Slow Cheetah.  I added a brand new json file

**Comment by davilimap** [comment] 2018-07-05 22:30
@TheMrAnderson what version of the SlowCheetah nuget package is installed in your project? The correct nuget package is [Microsoft.VisualStudio.SlowCheetah](https://www.nuget.org/packages/Microsoft.VisualStudio.SlowCheetah) which contains versions 3.0.56 and above, that support JSON transformations

**Comment by TheMrAnderson** [comment] 2018-07-06 13:29
My apologies.  I thought this issue was caused by Slow Cheetah, but it was caused by a previous extension I tried to use to transform JSON files.  It wrote some config lines in my .csproj file that I had to manually remove.  Once those were gone, Slow Cheetah did it's job.

**Comment by davilimap** [comment] 2018-07-18 17:32
Closing for now, since it seems to be fixed. Please reopen if more assistance is needed.

**Closed by davilimap** 2018-07-18 17:32 UTC
